---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/companies/{companyId}/workers/{companyMemberId}/roles":
    post:
      tags:
      - company-controller
      operationId: assignRoleToWorker
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: companyMemberId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AssignRoleRequest"
        required: true
      responses:
        '200':
          description: OK
  "/companies/{companyId}/roles":
    get:
      tags:
      - company-controller
      operationId: listRoles
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/CompanyRoleResponse"
    post:
      tags:
      - company-controller
      operationId: createRole
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateRoleRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CompanyRoleResponse"
  "/companies/{companyId}/invite-code/regenerate":
    post:
      tags:
      - company-controller
      operationId: regenerateInviteCode
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UpdateCompanyResponse"
  "/companies/participate":
    post:
      tags:
      - company-controller
      operationId: participateCompany
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ParticipateCompanyRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ParticipateCompanyResponse"
  "/companies/create":
    post:
      tags:
      - company-controller
      operationId: createCompany
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateCompanyRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CreateCompanyResponse"
  "/auth/signup-email":
    post:
      tags:
      - auth-controller
      operationId: signupEmail
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignupEmailRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MemberResponse"
  "/auth/login":
    post:
      tags:
      - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LoginWithIdTokenRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MemberResponse"
  "/members/me":
    get:
      tags:
      - member-controller
      operationId: me
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MemberResponse"
    patch:
      tags:
      - member-controller
      operationId: updateMe
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateNameRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MemberResponse"
  "/companies/{companyId}":
    delete:
      tags:
      - company-controller
      operationId: deleteCompany
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
    patch:
      tags:
      - company-controller
      operationId: updateCompany
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateCompanyRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UpdateCompanyResponse"
  "/companies/{companyId}/workers":
    get:
      tags:
      - company-controller
      operationId: listWorkers
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/CompanyWorkerResponse"
  "/companies/{companyId}/workers/{companyMemberId}":
    delete:
      tags:
      - company-controller
      operationId: removeWorker
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: companyMemberId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
components:
  schemas:
    AssignRoleRequest:
      required:
      - roleIds
      type: object
      properties:
        roleIds:
          type: array
          items:
            type: string
            format: uuid
    CreateRoleRequest:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    CompanyRoleResponse:
      type: object
      properties:
        roleId:
          type: string
          format: uuid
        name:
          type: string
    UpdateCompanyResponse:
      type: object
      properties:
        companyId:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        inviteCode:
          type: string
    ParticipateCompanyRequest:
      required:
      - inviteCode
      type: object
      properties:
        inviteCode:
          type: string
    ParticipateCompanyResponse:
      type: object
      properties:
        companyId:
          type: string
          format: uuid
    CreateCompanyRequest:
      required:
      - companyAddress
      - companyName
      type: object
      properties:
        companyName:
          type: string
        companyAddress:
          type: string
    CreateCompanyResponse:
      type: object
      properties:
        companyId:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        inviteCode:
          type: string
    SignupEmailRequest:
      required:
      - email
      - name
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    MemberResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        firebaseUid:
          type: string
    LoginWithIdTokenRequest:
      required:
      - idToken
      type: object
      properties:
        idToken:
          type: string
    UpdateNameRequest:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    UpdateCompanyRequest:
      required:
      - address
      - name
      type: object
      properties:
        name:
          type: string
        address:
          type: string
    CompanyWorkerResponse:
      type: object
      properties:
        companyMemberId:
          type: string
          format: uuid
        name:
          type: string
        role:
          type: string
          enum:
          - OWNER
          - MANAGER
          - WORKER
        hourlyWage:
          type: integer
          format: int32
